name: iOS build

on:
  push:
    branches: [ main ]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-15

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Select Xcode version
        run: sudo xcode-select -switch /Applications/Xcode_16.2.app

      - name: Build for iOS Simulator
        run: |
          xcodebuild \
            -project Planersmen/Planersmen.xcodeproj \
            -scheme Planersmen \
            -destination 'platform=iOS Simulator,name=iPhone 16,OS=latest' \
            -configuration Debug \
            build

      - name: Upload build artifact
        if: success()
        uses: actions/upload-artifact@v4
        with:
          name: Planersmen-app
          path: build/Debug-iphonesimulator/**/*.app
